### ISSUE TITLE
Variants

### ISSUE THREAD

**Issue by WandererXII** [WandererXII/scalashogi#4]
Currently suggested:

- [ ] Okisaki shogi (https://github.com/WandererXII/lishogi/issues/527)
- [x] Annan shogi (https://github.com/WandererXII/lishogi/issues/475)
- [ ] Doubutsu shogi (https://github.com/WandererXII/lishogi/issues/473)
- [x] Chuushogi (https://github.com/WandererXII/lishogi/issues/472)
- [x] Kyotoshogi (https://github.com/WandererXII/lishogi/issues/471)
- [ ] Tori shogi (https://github.com/WandererXII/lishogi/issues/628)

**Comment by Rechefiltr-is-Fire** [comment]
I have a suggestion 
![image](https://user-images.githubusercontent.com/101206332/177982452-10da56af-8e9c-4e9f-bb6f-1f4ec92dc1bb.jpeg)
Atomic Shogi —
Like Atomic chess in Lichess. But on usual Shogi board with one difference: you can’t drop your pieces on promotion zone.

**Comment by SetTheorist** [comment]
Tenjiku shogi is the other playable large-board variant, though given the limited audience already for Chu Shogi, it might not be worth the effort.  It can lead to quite exciting games, allegedly, with the demon (who can burn multiple pieces in a single move), but I've never actually played a game of it.

**Comment by olekawaii** [comment]
I propose a filter for which variants could be added
1. The variant must be Japanese (created in japan)
2.  It must either be traditional (imo before 1700) or have a significant playerbase

I fear lishogi may turn into a chess variants website

**Comment by WandererXII** [comment]
I will be closing in favor of lishogi issues with variant tag - https://github.com/WandererXII/lishogi/issues?q=is%3Aopen+is%3Aissue+label%3Avariant



> I propose a filter for which variants could be added
> 
> 1. The variant must be Japanese (created in japan)
> 2. It must either be traditional (imo before 1700) or have a significant playerbase
> 
> I fear lishogi may turn into a chess variants website

I 100% agree with the second point, and mostly with the first, but in principle I would not oppose adding a variant with a 'large' playerbase just because it isn't Japanese, although I would consider it a point against adding it I guess...
